# Generated by Django 4.2.9 on 2024-02-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_images_delete_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
